-
 name: installation
 hosts: all
 tasks:
   -
    name: Install JAVA,TOMCAT,APACHE on ubuntu
    apt:
      name: ['apache2', 'openjdk-8-jdk']
    when:
        - ansible_facts['distribution'] == "Ubuntu"
   -
    name: Install JAVA,TOMCAT,APACHE on centos
    yum:
      name: ['httpd', 'java-1.8.0-openjdk']
    when:
      - ansible_facts['distribution'] == "CentOS"
   -
    name: Add group Tomcat
    group:
       name: tomcat
   -
    name: Add user Tomcat
    user:
       name: tomcat
       group: tomcat
       home: /usr/share/tomcat
       createhome: no
   -
    name: Download Tomcat
    get_url:
      url: http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.38/bin/apache-tomcat-8.5.38.tar.gz 
      dest: /opt/apache-tomcat-8.5.38.tar.gz
   -
    name: Extract archive
    command:  chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-8.5.38.tar.gz -C /opt/ creates=/opt/apache-tomcat-8.5.38
   -
    name: Start Tomcat
    file: 
      src: /opt/apache-tomcat-8.5.38
      path: /usr/share/tomcat 
      state: link
   -
    name: Configure Tomcat server
    file: 
      path: /usr/share/tomcat/ 
      owner: tomcat 
      group: tomcat 
      state: directory 
      recurse: yes
   -
    name: Install Tomcat init script
    copy:
      src: tomcat-initscript.sh
      dest: /etc/init.d/tomcat
      mode: 0755
   -
    name: Start Tomcat 
    systemd:
      name: tomcat 
      state: restarted 
